Отправка информации об обработанных исключений в firebase
BitCodersNN/unn-mobile pull request #266
Opened 2024-03-12 17:47 UTC by Namxobick

Также добавил для удобства кастомные ошибки и в методе получения профиля текущего пользователя .fromJson завернул в try catch, чтобы понять из-за чего у некоторых пользователей крашилось приложение.

2024-03-12 19:17 UTC, KriseevM requested changes

2024-03-12 19:17 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
> +  ///  1. Exception - если возникло непредвиденное исключение
`[Exception]` ?

2024-03-12 19:17 UTC, KriseevM commented on lib/core/services/interfaces/authorisation_refresh_service.dart
> +  /// Выбрасывает теже исключения, что и [AuthorisationService.auth]
```suggestion
  /// Выбрасывает те же исключения, что и [AuthorisationService.auth]
```

2024-03-12 19:24 UTC, Namxobick commented on lib/core/services/interfaces/authorisation_service.dart
> +  ///   1. SessionCookieException - если session cookie имеет значени null
[SessionCookieException ]

2024-03-12 19:24 UTC, Namxobick commented on lib/core/services/interfaces/authorisation_service.dart
> +  ///   2. CsrfValueException - если csrf value имеет значени null
[CsrfValueException ]

2024-03-12 19:24 UTC, Namxobick commented on lib/core/services/interfaces/authorisation_service.dart
> +  ///   3. Exception - если возникло непредвиденное исключение
[Exception]

2024-03-15 10:33 UTC, Namxobick commented
Добавить логирование во всех сервисах, когда statusCode != 200

2024-03-16 10:35 UTC, KriseevM approved these changes

2024-03-16 10:36 UTC, KriseevM commented
А
Пока ревьюил конфликты вылезли

2024-03-16 20:04 UTC, KriseevM approved these changes

2024-03-16 21:08 UTC, merged