Получение списка пользователей, которые лайкнули пост
BitCodersNN/unn-mobile pull request #316
Opened 2024-04-13 20:29 UTC by Namxobick

resolves #274

2024-04-19 19:27 UTC, Namxobick commented
Добавить документацию

2024-04-26 11:15 UTC, KriseevM requested changes

2024-04-26 11:15 UTC, KriseevM commented on lib/core/services/implementations/feed_stream_updater_service_impl.dart
> +          startPosFilesInData + (post.files ?? []).length - 1;
Может стоит просто индекс future для реакций оставить?
Чтоб не делать -1 здесь и +1 ниже

2024-04-26 11:15 UTC, KriseevM commented on lib/core/services/implementations/feed_stream_updater_service_impl.dart
> +        startPosFilesInData + endPosFilesInData,
Вместо сложения позиций - вынеси количество файлов в отдельную переменную и его прибавляй

2024-04-26 11:15 UTC, KriseevM commented on lib/core/services/implementations/feed_stream_updater_service_impl.dart
> +          .toList();
```suggestion
      List<FileData> filteredFiles = files
          .where((element) => element != null)
          .map((e) => e!)
          .toList();
```

Может так лучше будет (только форматтером проверь)

2024-04-26 11:56 UTC, KriseevM commented on lib/core/services/implementations/feed_stream_updater_service_impl.dart
> +          .toList();
вроде если два слеша поставить после files, то разделит по-нормальному https://stackoverflow.com/a/74176437/14116050

2024-04-26 12:08 UTC, Namxobick commented on lib/core/services/implementations/feed_stream_updater_service_impl.dart
> +        startPosFilesInData + endPosFilesInData,
здесь вообще не должно было быть сложения *_*

2024-04-26 13:18 UTC, KriseevM approved these changes

2024-04-26 13:19 UTC, merged